[target.thumbv6m-none-eabi]
runner = "arm-none-eabi-gdb -q -x openocd.gdb"

rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
