[target.thumbv6m-none-eabi]
runner =  "probe-rs-debugger debug --chip STM32G030F6Px --speed 24000 --probe-index 0 --protocol swd --connect-under-reset  --core-index 0 --flashing-enabled --reset-after-flashing --halt-after-reset --program-binary "

rustflags = [
  "-C", "link-arg=-Tlink.x",
  # "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
